version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
